# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args:
        - --allow-multiple-documents
    -   id: check-added-large-files
    -   id: check-ast
    -   id: detect-private-key
    -   id: check-case-conflict
    -   id: detect-aws-credentials
        args:
         - --allow-missing-credentials
    -   id: check-shebang-scripts-are-executable
    -   id: requirements-txt-fixer
    -   id: check-merge-conflict
    -   id: pretty-format-json
        args:
          - --autofix



-   repo: https://github.com/pre-commit/mirrors-isort # original isort conflicts with black
    rev: 'v5.9.1'
    hooks:
      - id: isort
        args: ["--profile", "black"]


-   repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.3'  # or any later Vulture version
    hooks:
      - id: vulture
        args: [--min-confidence=70, --exclude=tests/]
        files: ^[^/]+\.py$'




-   repo: https://github.com/pycqa/pylint # checks code or programming errors, helps enforcing a coding standard, sniffs for code smells and offers simple refactoring suggestions.
    rev: v2.8.3
    hooks:
      - id: pylint
        exclude: '.*\/migrations\/.*|.*\/settings\.py$|.*\/apps\.py$'
        args:
            - --disable=C0114
            - --disable=C0115
            - --disable=W0613
            # - --disable=R0801
            - --disable=E0401
            - --disable=R0903
            - --disable=W0611
            - --disable=C0301
            - --disable=W0104
            - --disable=R0914
            - --disable=R0912
            - --disable=R0201


        types: [ python ]

-   repo: https://github.com/psf/black # strict code formatter to maintain consistency across projects and developers
    rev: 22.3.0
    hooks:
      - id: black

-   repo: https://github.com/jendrikseipp/vulture # finds unused code
    rev: 'v2.3'
    hooks:
      - id: vulture
        args: ['.', --min-confidence=80]


# -   repo: https://github.com/pycqa/pylint # checks code or programming errors, helps enforcing a coding standard, sniffs for code smells and offers simple refactoring suggestions.
#     rev: v2.8.3
#     hooks:
#       - id: pylint
#         exclude: '.*\/migrations\/.*|.*\/settings\.py$|.*\/apps\.py$|main.py'
#         args:
#             - --disable=C0114
#             - --disable=C0115
#             - --disable=E0401
#             - --disable=R0903
#             - --disable=W0611
#             - --disable=C0301
#             - --disable=W0104
#             - --disable=R0914
#             - --disable=R0912
#             - --ignored-argument-names=arg|args|kwargs|self


#         types: [ python ]



# -   repo: local
#     hooks:
#       - id: django-test
#         name: django-test
#         entry: python3 manage.py test
#         always_run: true
#         pass_filenames: false
#         language: system
